check that required params are present

diff --git a/assets/in b/assets/in
--- a/assets/in
+++ b/assets/in
@@ -22,6 +22,25 @@ username=$(jq -r '.source.username // ""' < $payload)
 password=$(jq -r '.source.password // ""' < $payload)
 team=$(jq -r '.source.team // ""' < $payload)
 
+if [ -z "$uri" ]; then
+  echo "invalid payload (missing uri):" >&2
+  cat $payload >&2
+  exit 1
+fi
+if [ -z "$username" ]; then
+  echo "invalid payload (missing username):" >&2
+  cat $payload >&2
+  exit 1
+fi
+if [ -z "$password" ]; then
+  echo "invalid payload (missing password):" >&2
+  cat $payload >&2
+  exit 1
+fi
+if [ -z "$team" ]; then
+  team=main
+fi
+
 wget --no-check-certificate "${uri}/api/v1/cli?arch=amd64&platform=linux" -O fly
 
 chmod +x fly
